package kr.co.infovine.dkmm.mapper.common;

import kr.co.infovine.dkmm.db.model.common.TCommonCodeModel;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;

public interface TCommonCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_code
     *
     * @mbg.generated Tue Sep 13 15:42:13 KST 2022
     */
    int deleteByPrimaryKey(@Param("codeGroup") String codeGroup, @Param("codeValue") String codeValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_code
     *
     * @mbg.generated Tue Sep 13 15:42:13 KST 2022
     */
    int insert(TCommonCodeModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_code
     *
     * @mbg.generated Tue Sep 13 15:42:13 KST 2022
     */
    TCommonCodeModel selectByPrimaryKey(@Param("codeGroup") String codeGroup, @Param("codeValue") String codeValue);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_code
     *
     * @mbg.generated Tue Sep 13 15:42:13 KST 2022
     */
    List<TCommonCodeModel> selectByCodeGroup(@Param("codeGroup") String codeGroup);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_code
     *
     * @mbg.generated Tue Sep 13 15:42:13 KST 2022
     */
    List<TCommonCodeModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common_code
     *
     * @mbg.generated Tue Sep 13 15:42:13 KST 2022
     */
    int updateByPrimaryKey(TCommonCodeModel row);
    
    List<HashMap<String, Object>> selectByCodeCategory();

    List<TCommonCodeModel> selectByPromotion(@Param("mode") String mode);
}